address.address_format.*:
  type: config_entity
  label: 'Address format'
  mapping:
    countryCode:
      type: string
      label: 'Country code'
    format:
      type: text
      label: 'Format'
    requiredFields:
      type: sequence
      label: 'Required fields'
      sequence:
        - type: string
    uppercaseFields:
      type: sequence
      label: 'Uppercase Fields'
      sequence:
        - type: string
    administrativeAreaType:
      type: string
      label: 'Administrative area type'
    localityType:
      type: string
      label: 'Locality type'
    dependentLocalityType:
      type: string
      label: 'Dependent locality type'
    postalCodeType:
      type: string
      label: 'Postal code type'
    postalCodePattern:
      type: string
      label: 'Postal code pattern'
    postalCodePrefix:
      type: string
      label: 'Postal code prefix'

field.field_settings.address:
  type: mapping
  label: 'Address field settings'
  mapping:
    available_countries:
      type: sequence
      label: 'Available countries'
      sequence:
        - type: string
    fields:
      type: sequence
      label: 'Used fields'
      sequence:
        - type: string

field.widget.settings.address_default:
  type: mapping
  label: 'Default address formatter settings'
  mapping:
    default_country:
      type: string
      label: 'Default country'

address.zone.*:
  type: config_entity
  label: 'Zone'
  mapping:
    id:
      type: string
      label: 'Zone id'
    name:
      type: string
      label: 'Zone name'
    scope:
      type: string
      label: 'Zone scope'
    priority:
      type: integer
      label: 'Zone priority'
    members:
      type: sequence
      label: 'Zone members'
      sequence:
        type: address.zone_member.[%key]

address.zone_member.*:
  type: mapping
  label: 'Zone member settings'
  mapping:
    type:
      type: string
      label: 'Zone member type'

address.zone_member.country:
  type: mapping
  label: 'Zone member (country-based)'
  mapping:
    countryCode:
      type: string
      label: 'Country code'
    administrativeArea:
      type: string
      label: 'Administrative area'
    locality:
      type: string
      label: 'Locality'
    dependentLocality:
      type: string
      label: 'Code'
    name:
      type: label
      label: 'Name'
      translatable: true

address.zone_member.zone:
  type: mapping
  label: 'Zone member (zone-based)'
  mapping:
    zone_id:
      type: string
      label: 'Zone ID'

